print("Escribe 3 números para saber cual es el mayor y menor")
num1 = int(input())
num2 = int(input())
num3 = int(input())
print("El núemro mayor es5: ", max(num1, num2, num3))
print("El número menor es:",min(num1, num2,num3))